### ISSUE TITLE
Backend says Invalid URL on making any request.

### ISSUE THREAD

**Issue by asifrahaman13** [ItzCrazyKns/Perplexica#184]
Hi. I tried to install and run the application. I am following the CONTRIBUTING.md page. 

I am running in development mode. Both backend and front end is running. But when I try to make any request the backend crashes. 

![Screenshot from 2024-06-10 23-45-32](https://github.com/ItzCrazyKns/Perplexica/assets/97652031/7461790a-e7ca-43ca-a892-6575745d6106)

Steps to reporoduce:

Clone the repository.

Follow the CONTRIBUTING.md instructions

**Comment by since1q80** [comment]
I encounter the same problem.I even changed the ollama config in config.toml and rebuild.It still report the same problem.
2024-06-12 10:18:30 perplexica-backend-1   | node:internal/process/promises:289
2024-06-12 10:18:30 perplexica-backend-1   |             triggerUncaughtException(err, true /* fromPromise */);
2024-06-12 10:18:30 perplexica-backend-1   |             ^
2024-06-12 10:18:30 perplexica-backend-1   | 
2024-06-12 10:18:30 perplexica-backend-1   | TypeError: Invalid URL
2024-06-12 10:18:30 perplexica-backend-1   |     at new URL (node:internal/url:775:36)
2024-06-12 10:18:30 perplexica-backend-1   |     at OpenAI.buildURL (/home/perplexica/node_modules/openai/core.js:318:15)
2024-06-12 10:18:30 perplexica-backend-1   |     at OpenAI.buildRequest (/home/perplexica/node_modules/openai/core.js:199:26)
2024-06-12 10:18:30 perplexica-backend-1   |     at OpenAI.makeRequest (/home/perplexica/node_modules/openai/core.js:274:44)
2024-06-12 10:18:30 perplexica-backend-1   |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-06-12 10:18:30 perplexica-backend-1   |     at async /home/perplexica/node_modules/@langchain/openai/dist/chat_models.cjs:684:29
2024-06-12 10:18:30 perplexica-backend-1   |     at async RetryOperation._fn (/home/perplexica/node_modules/p-retry/index.js:50:12) {
2024-06-12 10:18:30 perplexica-backend-1   |   code: 'ERR_INVALID_URL',
2024-06-12 10:18:30 perplexica-backend-1   |   input: 'null/chat/completions'
2024-06-12 10:18:30 perplexica-backend-1   | }
2024-06-12 10:18:30 perplexica-backend-1   | 
2024-06-12 10:18:30 perplexica-backend-1   | Node.js v20.8.1
2024-06-12 10:18:30 perplexica-backend-1   | error Command failed with exit code 1.
2024-06-12 10:18:30 perplexica-backend-1   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2024-06-12 10:18:31 perplexica-backend-1   | yarn run v1.22.19
2024-06-12 10:18:31 perplexica-backend-1   | $ node dist/app.js
2024-06-12 10:18:31 perplexica-backend-1   | info: WebSocket server started on port 3001
2024-06-12 10:18:31 perplexica-backend-1   | info: Server is running on port 3001
perplexica-frontend-1 exited with code 0
perplexica-frontend-1 exited with code 1
perplexica-backend-1 exited with code 0
perplexica-backend-1 exited with code 1
searxng-1              | 2024-06-12T02:19:24.832148636Z ...brutally killing workers...
2024-06-12 10:19:26 searxng-1              | worker 1 buried after 2 seconds
2024-06-12 10:19:26 searxng-1              | worker 2 buried after 2 seconds
2024-06-12 10:19:26 searxng-1              | worker 3 buried after 2 seconds
2024-06-12 10:19:26 searxng-1              | worker 4 buried after 2 seconds
2024-06-12 10:19:26 searxng-1              | worker 5 buried after 2 seconds
2024-06-12 10:19:26 searxng-1              | worker 6 buried after 2 seconds
2024-06-12 10:19:26 searxng-1              | worker 7 buried after 2 seconds
2024-06-12 10:19:26 searxng-1              | worker 8 buried after 2 seconds
2024-06-12 10:19:26 searxng-1              | binary reloading uWSGI...
2024-06-12 10:19:26 searxng-1              | chdir() to /usr/local/searxng
2024-06-12 10:19:26 searxng-1              | closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
2024-06-12 10:19:26 searxng-1              | found fd 3 mapped to socket 0 (0.0.0.0:8080)
2024-06-12 10:19:27 searxng-1              | running /usr/sbin/uwsgi
2024-06-12 10:19:27 searxng-1              | [uWSGI] getting INI configuration from /etc/searxng/uwsgi.ini
2024-06-12 10:19:27 searxng-1              | [uwsgi-static] added mapping for /static => /usr/local/searxng/searx/static
2024-06-12 10:19:27 searxng-1              | *** Starting uWSGI 2.0.23 (64bit) on [Wed Jun 12 02:19:27 2024] ***
2024-06-12 10:19:27 searxng-1              | compiled with version: 13.2.1 20231014 on 30 November 2023 14:34:33
2024-06-12 10:19:27 searxng-1              | os: Linux-6.6.16-linuxkit #1 SMP Fri Feb 16 11:54:02 UTC 2024
2024-06-12 10:19:27 searxng-1              | nodename: 57367f5a66bd
2024-06-12 10:19:27 searxng-1              | machine: aarch64
2024-06-12 10:19:27 searxng-1              | clock source: unix
2024-06-12 10:19:27 searxng-1              | pcre jit disabled
2024-06-12 10:19:27 searxng-1              | detected number of CPU cores: 8
2024-06-12 10:19:27 searxng-1              | current working directory: /usr/local/searxng
2024-06-12 10:19:27 searxng-1              | detected binary path: /usr/sbin/uwsgi
2024-06-12 10:19:27 searxng-1              | chdir() to /usr/local/searxng/searx/
2024-06-12 10:19:27 searxng-1              | your memory page size is 4096 bytes
2024-06-12 10:19:27 searxng-1              | detected max file descriptor number: 1048576
2024-06-12 10:19:27 searxng-1              | building mime-types dictionary from file /etc/mime.types...1390 entry found
2024-06-12 10:19:27 searxng-1              | lock engine: pthread robust mutexes
2024-06-12 10:19:27 searxng-1              | thunder lock: disabled (you can enable it with --thunder-lock)
2024-06-12 10:19:27 searxng-1              | uwsgi socket 0 inherited INET address 0.0.0.0:8080 fd 3
2024-06-12 10:19:27 searxng-1              | Python version: 3.11.9 (main, Apr 14 2024, 13:40:00) [GCC 13.2.1 20231014]
2024-06-12 10:19:27 searxng-1              | Python main interpreter initialized at 0xffffb028aac0
2024-06-12 10:19:27 searxng-1              | python threads support enabled
2024-06-12 10:19:27 searxng-1              | your server socket listen backlog is limited to 100 connections
2024-06-12 10:19:27 searxng-1              | your mercy for graceful operations on workers is 60 seconds
2024-06-12 10:19:27 searxng-1              | mapped 1086048 bytes (1060 KB) for 32 cores
2024-06-12 10:19:27 searxng-1              | *** Operational MODE: preforking+threaded ***
2024-06-12 10:19:27 searxng-1              | added /usr/local/searxng/ to pythonpath.
2024-06-12 10:19:27 searxng-1              | gracefully (RE)spawned uWSGI master process (pid: 7)
2024-06-12 10:19:27 searxng-1              | spawned uWSGI worker 1 (pid: 234, cores: 4)
2024-06-12 10:19:27 searxng-1              | spawned uWSGI worker 2 (pid: 235, cores: 4)
2024-06-12 10:19:27 searxng-1              | spawned 4 offload threads for uWSGI worker 2
2024-06-12 10:19:27 searxng-1              | spawned uWSGI worker 3 (pid: 239, cores: 4)
2024-06-12 10:19:27 searxng-1              | spawned 4 offload threads for uWSGI worker 4
2024-06-12 10:19:27 searxng-1              | spawned uWSGI worker 4 (pid: 243, cores: 4)
2024-06-12 10:19:27 searxng-1              | spawned 4 offload threads for uWSGI worker 1
2024-06-12 10:19:27 searxng-1              | spawned 4 offload threads for uWSGI worker 3
2024-06-12 10:19:27 searxng-1              | spawned uWSGI worker 5 (pid: 251, cores: 4)
2024-06-12 10:19:27 searxng-1              | spawned uWSGI worker 6 (pid: 255, cores: 4)
2024-06-12 10:19:27 searxng-1              | spawned 4 offload threads for uWSGI worker 6
2024-06-12 10:19:27 searxng-1              | spawned uWSGI worker 7 (pid: 262, cores: 4)
2024-06-12 10:19:27 searxng-1              | spawned 4 offload threads for uWSGI worker 5
2024-06-12 10:19:27 searxng-1              | spawned uWSGI worker 8 (pid: 265, cores: 4)
2024-06-12 10:19:27 searxng-1              | spawned 4 offload threads for uWSGI worker 8
2024-06-12 10:19:27 searxng-1              | spawned 4 offload threads for uWSGI worker 7
2024-06-12 10:19:30 searxng-1              | WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0xffffb028aac0 pid: 255 (default app)
2024-06-12 10:19:30 searxng-1              | WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0xffffb028aac0 pid: 265 (default app)
2024-06-12 10:19:30 searxng-1              | WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0xffffb028aac0 pid: 243 (default app)
2024-06-12 10:19:30 searxng-1              | WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0xffffb028aac0 pid: 251 (default app)
2024-06-12 10:19:30 searxng-1              | WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0xffffb028aac0 pid: 234 (default app)
2024-06-12 10:19:30 searxng-1              | WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0xffffb028aac0 pid: 239 (default app)
2024-06-12 10:19:30 searxng-1              | WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0xffffb028aac0 pid: 262 (default app)
2024-06-12 10:19:30 searxng-1              | WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0xffffb028aac0 pid: 235 (default app)
searxng-1 exited with code 0

**Comment by since1q80** [comment]
I think i have settled the problem down.When visiting the localhost:3000,just to config in the setting page and everything is fine then.

**Comment by asifrahaman13** [comment]
@since1q80 

Can you explain a bit more with some screenshots.

**Comment by since1q80** [comment]
<img width="441" alt="731718184289_ pic copy" src="https://github.com/ItzCrazyKns/Perplexica/assets/445043/1b080d17-b177-4dcd-9bb1-75a12b73a0b3">

You should config the model in the web page via the "setting" button which is at the left buttom corner.

> @since1q80
> 
> Can you explain a bit more with some screenshots.

**Comment by asifrahaman13** [comment]
@since1q80 

Thanks man. It worked. 

I need another help.  

How to configure for the SEARXNG. It runs on port 8888

I am getting the following errors when the agent is trying for google search.

![Screenshot from 2024-06-12 16-09-30](https://github.com/ItzCrazyKns/Perplexica/assets/97652031/13161a2c-181e-4e70-bfc9-3b4e29e5f3ef)


No endpoint ```"http://localhost:32768"``` is present from searchxng. 

So I tried with the 8888. But I am getting the 403 error

**Comment by asifrahaman13** [comment]
@PallaviDaDivr 

Nothing is clearly written in the documentation about that. So I am not really sure how to exactly set up.  If you find something please let me know too.

**Comment by since1q80** [comment]
> @since1q80 
> 
> Thanks man. It worked. 
> 
> I need another help.  
> 
> How to configure for the SEARXNG. It runs on port 8888
> 
> I am getting the following errors when the agent is trying for google search.
> 
> ![Screenshot from 2024-06-12 16-09-30](https://github.com/ItzCrazyKns/Perplexica/assets/97652031/13161a2c-181e-4e70-bfc9-3b4e29e5f3ef)
> 
> 
> No endpoint ```"http://localhost:32768"``` is present from searchxng. 
> 
> So I tried with the 8888. But I am getting the 403 error.
> 
> 
> Note that the application is working fine if serch is not requried (where the open ai can give answer by itself)

Did you use the docker which will make the things much simpler and easier?

**Comment by asifrahaman13** [comment]
@since1q80 

That not feasible option for development. :(

**Comment by since1q80** [comment]
> @since1q80
> 
> That not feasible option for development. :(

I just tried in development mode and there are some tricky steps which is ok for me.
1.Since the SearNXG is just a service and is started via docker,you could start it.But bear in mind,you do not use the command like "docker run -d --name searxng -p 4000:8080 searxng/searxng" in the terminal to start.But you should use the docker client to start the searxng service like the pic
![image](https://github.com/ItzCrazyKns/Perplexica/assets/445043/57ffa008-28cf-441e-80ad-d1c645a7b1f5)
2.In the config.toml,you should set the port as 4000
[API_ENDPOINTS]
OLLAMA = ""
SEARXNG = "http://localhost:4000"

**Comment by grrowl** [comment]
really should update the default config.toml here to match the custom docker-compose

**Comment by ItzCrazyKns** [comment]
> @since1q80
> 
> Thanks man. It worked.
> 
> I need another help.
> 
> How to configure for the SEARXNG. It runs on port 8888
> 
> I am getting the following errors when the agent is trying for google search.
> 
> ![Screenshot from 2024-06-12 16-09-30](https://private-user-images.githubusercontent.com/97652031/338932704-13161a2c-181e-4e70-bfc9-3b4e29e5f3ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NDE3MTMsIm5iZiI6MTcxOTU0MTQxMywicGF0aCI6Ii85NzY1MjAzMS8zMzg5MzI3MDQtMTMxNjFhMmMtMTgxZS00ZTcwLWJmYzktM2I0ZTI5ZTVmM2VmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDAyMjMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmYmU0MTBlYWRiOWZlOTU5ZjZmMjIzYTVlZDI4YjU1NzkzNGU4ZGMyNWMxYzM2OGI1Y2UzODY3MTM2NzBhZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uRg_tiCAna0myPbh3vII4RqwZhkDDukrHHuPLzWvUY0)
> 
> No endpoint `"http://localhost:32768"` is present from searchxng.
> 
> So I tried with the 8888. But I am getting the 403 error.
> 
> Note that the application is working fine if serch is not requried (where the open ai can give answer by itself)

Hi, you need to add `JSON` format in SearXNG settings. The SearXNG container we provide already has this settings enabled so you can either use that or add the `JSON` format in the settings file of your hosted SearXNG.
