### ISSUE TITLE
error: undefined - MacOS Ollama

### ISSUE THREAD

**Issue by nicolas-g** [ItzCrazyKns/Perplexica#224]
**Describe the bug**
I'm not able to search running Perplexica as a docker container locally and Ollama.

**To Reproduce**

Ollama installation
```bash
$ brew install ollama 
$ brew services start ollama
$ ollama pull llama3:latest
```

confirm the service is working
```bash
$ curl  http://127.0.0.1:11434

Ollama is running%
```

config file:
```config.toml
[API_ENDPOINTS]
SEARXNG = "http://localhost:32768" # SearxNG API URL
OLLAMA = "http://host.docker.internal:11434"
```

open http://localhost:3000 and do any search ...

**Expected behavior**
Perplexica be able to return answers for any query with no errors

**Additional context**

Anytime I try to search for something I see `error: undefined` in the log entries:

```bash
docker logs perplexica-perplexica-backend-1 -f
yarn run v1.22.19
$ node dist/app.js
info: WebSocket server started on port 3001
info: Server is running on port 3001


error: undefined
error: undefined
```

**Comment by ItzCrazyKns** [comment]
I'll try to reproduce

**Comment by delfireinoso** [comment]
I run Perplexica on a Mac. Ollam is running on the Mac app because I see that Ollama has a pending update with the icon.

if you follow the Perplexica compse installation, and you put OLLAMA = "http://host.docker.internal:11434" on the Config.toml file you should have Perplexica running. 

By default Perplexica frontend is on localhost:3000, see if you have anything listening there

**Comment by Arun-chaitanya** [comment]
Getting the same bug

**Comment by Arun-chaitanya** [comment]
<img width="1440" alt="Screenshot 2024-06-29 at 3 00 41 PM" src="https://github.com/ItzCrazyKns/Perplexica/assets/44457256/10e6227a-eb44-4d34-98c8-f16d4e8e58b4">
When I try to run it for first time.

**Comment by ItzCrazyKns** [comment]
> <img alt="Screenshot 2024-06-29 at 3 00 41 PM" width="1440" src="https://private-user-images.githubusercontent.com/44457256/344382446-10e6227a-eb44-4d34-98c8-f16d4e8e58b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NTYyOTcsIm5iZiI6MTcxOTY1NTk5NywicGF0aCI6Ii80NDQ1NzI1Ni8zNDQzODI0NDYtMTBlNjIyN2EtZWI0NC00ZDM0LTk4YzgtZjE2ZDRlOGU1OGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDEwMTMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhYWIyMjNmMjVhY2JjMzUzOGY3NzRhOWNkMzkxNjdkODAwNWE4NmI0MjcwMGY3ODM0NDQ2YjNkNmMzODY5OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.59qbur_OiIiyHIsunx4KMwsU90lSn7NXfj6z-IrloPA"> When I try to run it for first time.

What are the logs from the backend container

**Comment by Arun-chaitanya** [comment]
2024-06-29 15:08:06 yarn run v1.22.19
2024-06-29 15:08:06 $ node dist/app.js
2024-06-29 15:08:06 info: WebSocket server started on port 3001
2024-06-29 15:08:06 info: Server is running on port 3001
2024-06-29 15:08:15 error: undefined
2024-06-29 15:08:16 error: undefined
2024-06-29 15:08:25 node:internal/process/promises:289
2024-06-29 15:08:25             triggerUncaughtException(err, true /* fromPromise */);
2024-06-29 15:08:25             ^
2024-06-29 15:08:25 
2024-06-29 15:08:25 TypeError: Invalid URL
2024-06-29 15:08:25     at new URL (node:internal/url:775:36)
2024-06-29 15:08:25     at OpenAI.buildURL (/home/perplexica/node_modules/openai/core.js:318:15)
2024-06-29 15:08:25     at OpenAI.buildRequest (/home/perplexica/node_modules/openai/core.js:199:26)
2024-06-29 15:08:25     at OpenAI.makeRequest (/home/perplexica/node_modules/openai/core.js:274:44)
2024-06-29 15:08:25     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-06-29 15:08:25     at async /home/perplexica/node_modules/@langchain/openai/dist/chat_models.cjs:684:29
2024-06-29 15:08:25     at async RetryOperation._fn (/home/perplexica/node_modules/p-retry/index.js:50:12) {
2024-06-29 15:08:25   code: 'ERR_INVALID_URL',
2024-06-29 15:08:25   input: 'null/chat/completions'
2024-06-29 15:08:25 }
2024-06-29 15:08:25 
2024-06-29 15:08:25 Node.js v20.8.1
2024-06-29 15:08:25 error Command failed with exit code 1.
2024-06-29 15:08:25 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2024-06-29 15:08:25 yarn run v1.22.19
2024-06-29 15:08:25 $ node dist/app.js
2024-06-29 15:08:25 info: WebSocket server started on port 3001
2024-06-29 15:08:25 info: Server is running on port 3001

**Comment by ItzCrazyKns** [comment]
> ```
> 2024-06-29 15:08:06 yarn run v1.22.19
> 2024-06-29 15:08:06 $ node dist/app.js
> 2024-06-29 15:08:06 info: WebSocket server started on port 3001
> 2024-06-29 15:08:06 info: Server is running on port 3001
> 2024-06-29 15:08:15 error: undefined
> 2024-06-29 15:08:16 error: undefined
> 2024-06-29 15:08:25 node:internal/process/promises:289
> 2024-06-29 15:08:25             triggerUncaughtException(err, true /* fromPromise */);
> 2024-06-29 15:08:25             ^
> 2024-06-29 15:08:25 
> 2024-06-29 15:08:25 TypeError: Invalid URL
> 2024-06-29 15:08:25     at new URL (node:internal/url:775:36)
> 2024-06-29 15:08:25     at OpenAI.buildURL (/home/perplexica/node_modules/openai/core.js:318:15)
> 2024-06-29 15:08:25     at OpenAI.buildRequest (/home/perplexica/node_modules/openai/core.js:199:26)
> 2024-06-29 15:08:25     at OpenAI.makeRequest (/home/perplexica/node_modules/openai/core.js:274:44)
> 2024-06-29 15:08:25     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 2024-06-29 15:08:25     at async /home/perplexica/node_modules/@langchain/openai/dist/chat_models.cjs:684:29
> 2024-06-29 15:08:25     at async RetryOperation._fn (/home/perplexica/node_modules/p-retry/index.js:50:12) {
> 2024-06-29 15:08:25   code: 'ERR_INVALID_URL',
> 2024-06-29 15:08:25   input: 'null/chat/completions'
> 2024-06-29 15:08:25 }
> 2024-06-29 15:08:25 
> 2024-06-29 15:08:25 Node.js v20.8.1
> 2024-06-29 15:08:25 error Command failed with exit code 1.
> 2024-06-29 15:08:25 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 2024-06-29 15:08:25 yarn run v1.22.19
> 2024-06-29 15:08:25 $ node dist/app.js
> 2024-06-29 15:08:25 info: WebSocket server started on port 3001
> 2024-06-29 15:08:25 info: Server is running on port 3001
> ```

Have you configured the OpenAI API key or the Groq API key or the Ollama address? Once of them is required for Perplexica to work.

**Comment by Arun-chaitanya** [comment]
Sorry for late reply. Yes I gave Ollama docker port address, which was successfully running in my local but it still did not work

**Comment by Arun-chaitanya** [comment]
[GENERAL]
PORT = 3001 # Port to run the server on
SIMILARITY_MEASURE = "cosine" # "cosine" or "dot"

[API_KEYS]
OPENAI = "" # OpenAI API key - sk-1234567890abcdef1234567890abcdef
GROQ = "" # Groq API key - gsk_1234567890abcdef1234567890abcdef

[API_ENDPOINTS]
SEARXNG = "http://localhost:32768" # SearxNG API URL
OLLAMA = "http://host.docker.internal:11434" # Ollama API URL - http://host.docker.internal:11434

**Comment by ItzCrazyKns** [comment]
What OS are you on?

> [GENERAL] PORT = 3001 # Port to run the server on SIMILARITY_MEASURE = "cosine" # "cosine" or "dot"
> 
> [API_KEYS] OPENAI = "" # OpenAI API key - sk-1234567890abcdef1234567890abcdef GROQ = "" # Groq API key - gsk_1234567890abcdef1234567890abcdef
> 
> [API_ENDPOINTS] SEARXNG = "http://localhost:32768" # SearxNG API URL OLLAMA = "http://host.docker.internal:11434" # Ollama API URL - http://host.docker.internal:11434

**Comment by rb81** [comment]
+1 - Getting the same issue. I'm running Ollama on Ubuntu Server. IP address and port set in the Perplexica config works on all other apps. Inference seems to be triggered, but after about 30 seconds Perplexica throws the following error:

> Failed to connect to the server. Please try again later.

**Comment by ItzCrazyKns** [comment]
> +1 - Getting the same issue. I'm running Ollama on Ubuntu Server. IP address and port set in the Perplexica config works on all other apps. Inference seems to be triggered, but after about 3 seconds Perplexica throws the following error:
> 
> > Failed to connect to the server. Please try again later.

What are the logs from the backend container?

**Comment by Arun-chaitanya** [comment]
> What OS are you on?
> 
> > [GENERAL] PORT = 3001 # Port to run the server on SIMILARITY_MEASURE = "cosine" # "cosine" or "dot"
> > [API_KEYS] OPENAI = "" # OpenAI API key - sk-1234567890abcdef1234567890abcdef GROQ = "" # Groq API key - gsk_1234567890abcdef1234567890abcdef
> > [API_ENDPOINTS] SEARXNG = "http://localhost:32768" # SearxNG API URL OLLAMA = "http://host.docker.internal:11434" # Ollama API URL - http://host.docker.internal:11434

Version 14.3 (23D56) MacOS Sonoma

**Comment by rb81** [comment]
@Arun-chaitanya @ItzCrazyKns - Got this working. The service expects a fake GROQ API key for this to work. Using `sk-proj-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx` gets the service to run with Ollama.

**Comment by rb81** [comment]
> > ```
> > 2024-06-29 15:08:06 yarn run v1.22.19
> > 2024-06-29 15:08:06 $ node dist/app.js
> > 2024-06-29 15:08:06 info: WebSocket server started on port 3001
> > 2024-06-29 15:08:06 info: Server is running on port 3001
> > 2024-06-29 15:08:15 error: undefined
> > 2024-06-29 15:08:16 error: undefined
> > 2024-06-29 15:08:25 node:internal/process/promises:289
> > 2024-06-29 15:08:25             triggerUncaughtException(err, true /* fromPromise */);
> > 2024-06-29 15:08:25             ^
> > 2024-06-29 15:08:25 
> > 2024-06-29 15:08:25 TypeError: Invalid URL
> > 2024-06-29 15:08:25     at new URL (node:internal/url:775:36)
> > 2024-06-29 15:08:25     at OpenAI.buildURL (/home/perplexica/node_modules/openai/core.js:318:15)
> > 2024-06-29 15:08:25     at OpenAI.buildRequest (/home/perplexica/node_modules/openai/core.js:199:26)
> > 2024-06-29 15:08:25     at OpenAI.makeRequest (/home/perplexica/node_modules/openai/core.js:274:44)
> > 2024-06-29 15:08:25     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> > 2024-06-29 15:08:25     at async /home/perplexica/node_modules/@langchain/openai/dist/chat_models.cjs:684:29
> > 2024-06-29 15:08:25     at async RetryOperation._fn (/home/perplexica/node_modules/p-retry/index.js:50:12) {
> > 2024-06-29 15:08:25   code: 'ERR_INVALID_URL',
> > 2024-06-29 15:08:25   input: 'null/chat/completions'
> > 2024-06-29 15:08:25 }
> > 2024-06-29 15:08:25 
> > 2024-06-29 15:08:25 Node.js v20.8.1
> > 2024-06-29 15:08:25 error Command failed with exit code 1.
> > 2024-06-29 15:08:25 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> > 2024-06-29 15:08:25 yarn run v1.22.19
> > 2024-06-29 15:08:25 $ node dist/app.js
> > 2024-06-29 15:08:25 info: WebSocket server started on port 3001
> > 2024-06-29 15:08:25 info: Server is running on port 3001
> > ```
> 
> Have you configured the OpenAI API key or the Groq API key or the Ollama address? Once of them is required for Perplexica to work.

I have an OpenAI API key configured as well as the Ollama server URI, but switching to Ollama seems to require a fake GROQ API key in order to work. Using `sk-proj-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx` gets it working for me. Just FYI, the error showing in the backend container logs was:

> error: Error loading Groq models: Error: OpenAI or Azure OpenAI API key not found

**Comment by ItzCrazyKns** [comment]
This issue is now resolved with https://github.com/ItzCrazyKns/Perplexica/commit/8539ce82ad4b289956fc9c57bd1fb505aa26451d. I'd recommend everyone to re-install Perplexica.

```sh
docker compose up -d --build
```

**Note**: Run this only after re-cloning the repository.

**Comment by rb81** [comment]
> This issue is now resolved with [8539ce8](https://github.com/ItzCrazyKns/Perplexica/commit/8539ce82ad4b289956fc9c57bd1fb505aa26451d). I'd recommend everyone to re-install Perplexica.
> 
> ```shell
> docker compose up -d --build
> ```
> 
> **Note**: Run this only after re-cloning the repository.

Did this but now nothing works. Do I need to change or do anything else?

**Comment by echeoquehaii** [comment]
Also experiencing the same wit Ollama

**Comment by rb81** [comment]
@ItzCrazyKns - After your last commit, it seems that having any Ollama settings in place stop Perplexica from working at all. Removing the Ollama URI and GROQ API key, and OpenAI settings work. As another using mentioned, Ollama is no longer an option in the "Chat Model Provider" list - just OpenAI and "Custom_OpenAI"

**Comment by ItzCrazyKns** [comment]
> @ItzCrazyKns - After your last commit, it seems that having any Ollama settings in place stop Perplexica from working at all. Removing the Ollama URI and GROQ API key, and OpenAI settings work. As another using mentioned, Ollama is no longer an option in the "Chat Model Provider" list - just OpenAI and "Custom_OpenAI"

Just did another commit, https://github.com/ItzCrazyKns/Perplexica/commit/27e6f5b9e1adeda5aeb5665a366d21d03cb07f30, that should help

**Comment by rb81** [comment]
> Just did another commit, [27e6f5b](https://github.com/ItzCrazyKns/Perplexica/commit/27e6f5b9e1adeda5aeb5665a366d21d03cb07f30), that should help

How should Ollama work now? The option is still not in the drop down. There's "Custom_OpenAI" and then the Ollama URI parameter separately to that. Earlier there was a separate option for Ollama in the model provider list...

**Comment by echeoquehaii** [comment]
I've re-cloned and re-set up everything, and now it works to me. Also had to clear cache and cookies, at the first attempt it was showing the same error

**Comment by rb81** [comment]
> I've re-cloned and re-set up everything, and now it works to me. Also had to clear cache and cookies, at the first attempt it was showing the same error

Are you able to get Ollama working?

**Comment by echeoquehaii** [comment]
> Are you able to get Ollama working?

Yes, it's working fine for me now!

**Comment by totorofly** [comment]
> > Just did another commit, [27e6f5b](https://github.com/ItzCrazyKns/Perplexica/commit/27e6f5b9e1adeda5aeb5665a366d21d03cb07f30), that should help
> 
> How should Ollama work now? The option is still not in the drop down. There's "Custom_OpenAI" and then the Ollama URI parameter separately to that. Earlier there was a separate option for Ollama in the model provider list...

the same error

**Comment by echeoquehaii** [comment]
> Are you able to get Ollama working?

Yes, it works for me with Ollama, after re setting up everything, and clearing cache and cookies of the webpage from my browser

**Comment by hanjinxin** [comment]
@nicolas-g   I have two environments, and currently my Mac can use ollama to call it normally,
<img width="453" alt="image" src="https://github.com/user-attachments/assets/4a123e7e-7070-445d-8735-6139cc2c6c3f">
Then I entered my Mac API interface into the Linux server, but it didn't seem to be correct and directly returned the message 'unable to connect'
<img width="484" alt="image" src="https://github.com/user-attachments/assets/3897d156-3e39-4d99-8390-d4d3c8747b5a">

I want to separate the backend from SEARXNG. Normally, only SEARXNG needs to open a proxy, right? The programs on the frontend and backend do not need a proxy, right   
<img width="740" alt="image" src="https://github.com/user-attachments/assets/7eb2354f-13c7-429a-9095-c4bbc39ad795">

**Comment by MehrCurry** [comment]
I was facing the same 'Invalid URL' error on my mac.

I tried some solution from this thread. Then I figured out, that config.toml is backed right in the backends docker image. So every time you do a change, **you have to rebuild** the docker images by doing

```
docker compose up -d --build
```
After that I got it running.

There is still another problem with the searxng container (Cannot load engine “gentoo”), but since I am using my already existing instance that does not matter for me.

see https://github.com/ItzCrazyKns/Perplexica/issues/257

**Comment by MehrCurry** [comment]
The problem re-appeared. Deleting the cookies solved it.
