### ISSUE TITLE
admin-password branch error

### ISSUE THREAD

**Issue by catninelife** [ItzCrazyKns/Perplexica#342]
```
 => ERROR [perplexica-frontend 5/5] RUN yarn build                                                                                                                57.3s
------
 > [perplexica-frontend 5/5] RUN yarn build:
0.323 yarn run v1.22.22
0.350 $ next build
0.972 Attention: Next.js now collects completely anonymous telemetry regarding usage.
0.973 This information is used to shape Next.js' roadmap and prioritize features.
0.973 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
0.973 https://nextjs.org/telemetry
0.973
1.067    ▲ Next.js 14.1.4
1.068
1.175    Creating an optimized production build ...
3.262 (node:40) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
3.262 (Use `node --trace-deprecation ...` to show where the warning was created)
15.95 (node:72) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
15.95 (Use `node --trace-deprecation ...` to show where the warning was created)
26.66  ✓ Compiled successfully
26.66    Linting and checking validity of types ...
35.29    Collecting page data ...
36.71    Generating static pages (0/6) ...
   Generating static pages (1/6)
   Generating static pages (2/6)
   Generating static pages (4/6)
47.15 TypeError: fetch failed
47.15     at node:internal/deps/undici/undici:13179:13
47.15     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
47.15     at async globalThis.fetch (/home/perplexica/.next/server/chunks/638.js:1:36484)
47.15     at async i (/home/perplexica/.next/server/app/library/page.js:1:7604) {
47.15   [cause]: ConnectTimeoutError: Connect Timeout Error
47.15       at onConnectTimeout (node:internal/deps/undici/undici:2331:28)
47.15       at node:internal/deps/undici/undici:2283:50
47.15       at Immediate._onImmediate (node:internal/deps/undici/undici:2315:13)
47.15       at process.processImmediate (node:internal/timers:491:21)
47.15       at process.callbackTrampoline (node:internal/async_hooks:130:17) {
47.15     code: 'UND_ERR_CONNECT_TIMEOUT'
47.15   }
47.15 }
57.16 TypeError: fetch failed
57.16     at node:internal/deps/undici/undici:13179:13
57.16     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
57.16     at async globalThis.fetch (/home/perplexica/.next/server/chunks/638.js:1:36484)
57.16     at async i (/home/perplexica/.next/server/app/library/page.js:1:7604) {
57.16   [cause]: ConnectTimeoutError: Connect Timeout Error
57.16       at onConnectTimeout (node:internal/deps/undici/undici:2331:28)
57.16       at node:internal/deps/undici/undici:2283:50
57.16       at Immediate._onImmediate (node:internal/deps/undici/undici:2315:13)
57.16       at process.processImmediate (node:internal/timers:491:21)
57.16       at process.callbackTrampoline (node:internal/async_hooks:130:17) {
57.16     code: 'UND_ERR_CONNECT_TIMEOUT'
57.16   }
57.16 }
57.16
57.16 Error occurred prerendering page "/library". Read more: https://nextjs.org/docs/messages/prerender-error
57.16
57.16 TypeError: fetch failed
57.16     at node:internal/deps/undici/undici:13179:13
57.16     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
57.16     at async globalThis.fetch (/home/perplexica/.next/server/chunks/638.js:1:36484)
57.16     at async i (/home/perplexica/.next/server/app/library/page.js:1:7604)
 ✓ Generating static pages (6/6)
57.19
57.19 > Export encountered errors on following paths:
57.19   /library/page: /library
57.22 error Command failed with exit code 1.
57.22 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn build" did not complete successfully: exit code: 1
```

**Comment by ItzCrazyKns** [comment]
Please try building the images again/
