### ISSUE TITLE
Docker compose up -d fails to start backend

### ISSUE THREAD

**Issue by jonny7737** [ItzCrazyKns/Perplexica#386]
**Describe the bug**
Backend service fails to start

**To Reproduce**
docker compose up -d

**Expected behavior**
Expected the backend to stay running
**Screenshots**

**Additional context**
docker logs for backend service:

[✓] Pulling schema from database...
2024-10-02 13:42:27 
2024-10-02 13:42:27 [i] No changes detected
2024-10-02 13:42:28 node:fs:441
2024-10-02 13:42:28     return binding.readFileUtf8(path, stringToFlags(options.flag));
2024-10-02 13:42:28                    ^
2024-10-02 13:42:28 
2024-10-02 13:42:28 Error: EISDIR: illegal operation on a directory, read
2024-10-02 13:42:28     at Object.readFileSync (node:fs:441:20)
2024-10-02 13:42:28     at loadConfig (/home/perplexica/dist/config.js:11:60)
2024-10-02 13:42:28     at getPort (/home/perplexica/dist/config.js:12:23)
2024-10-02 13:42:28     at Object.<anonymous> (/home/perplexica/dist/app.js:13:35)
2024-10-02 13:42:28     at Module._compile (node:internal/modules/cjs/loader:1546:14)
2024-10-02 13:42:28     at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
2024-10-02 13:42:28     at Module.load (node:internal/modules/cjs/loader:1317:32)
2024-10-02 13:42:28     at Module._load (node:internal/modules/cjs/loader:1127:12)
2024-10-02 13:42:28     at TracingChannel.traceSync (node:diagnostics_channel:315:14)
2024-10-02 13:42:28     at wrapModuleLoad (node:internal/modules/cjs/loader:217:24) {
2024-10-02 13:42:28   errno: -21,
2024-10-02 13:42:28   code: 'EISDIR',
2024-10-02 13:42:28   syscall: 'read'
2024-10-02 13:42:28 }
2024-10-02 13:42:28 
2024-10-02 13:42:28 Node.js v22.9.0
2024-10-02 13:42:28 error Command failed with exit code 1.
2024-10-02 13:42:28 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ItzCrazyKns** [comment]
Have you created a config.toml file? Delete the config.toml folder and rename sample.config.toml to config.toml and follow the steps again

**Comment by jonny7737** [comment]
> Have you created a config.toml file? Delete the config.toml folder and rename sample.config.toml to config.toml and follow the steps again

Yes, I followed the instructions.
What I hear you saying is to follow the instructions. The logs are from a completely new install - following the instructions.
Which part of the instructions did I missunderstand?

I'll try again using the instructions and report back.

**Comment by ItzCrazyKns** [comment]
> > Have you created a config.toml file? Delete the config.toml folder and rename sample.config.toml to config.toml and follow the steps again
> 
> Yes, I followed the instructions. What I hear you saying is to follow the instructions. The logs are from a completely new install - following the instructions. Which part of the instructions did I missunderstand?
> 
> I'll try again using the instructions and report back.

You didn't configured the config.toml file, so Docker thought it has a folder and linked it at as a volume. When FileSystem API is trying to execute read on it, it fails since its not a file but a folder. So configured the config.toml and delete the folder named config.toml

**Comment by jonny7737** [comment]
Step #4 of the instructions is for configuring the toml. I followed the instructions:. I configured the toml.

There is no folder named config.toml

**Comment by jonny7737** [comment]
Also, I had to change the frontend port [docker-compose.yaml] because port 3000 is already inuse.

**Comment by jonny7737** [comment]
I very much like the idea of this project. I have tried the docker install every few weeks since it first became available. None of the docker installs have run successfully but I will continue to try because i very much like the idea of this project.

**Comment by ItzCrazyKns** [comment]
> I very much like the idea of this project. I have tried the docker install every few weeks since it first became available. None of the docker installs have run successfully but I will continue to try because i very much like the idea of this project.

You can join our Discord server here: https://discord.gg/dw7KSCYv there I can provide you better  support to get you up and running.

**Comment by ItzCrazyKns** [comment]
What OS are you on and what is your CPU architecture

**Comment by jonny7737** [comment]
MacOS M2 Max 64GB

**Comment by ItzCrazyKns** [comment]
Closed as completed as on Discord

**Comment by Atomique** [comment]
Hi @ItzCrazyKns 

what was the solution? Would be nice to have a quick solution in the github issue to help people out that have the same problem. 

Thanks a lot and have a nice day!

**Comment by ItzCrazyKns** [comment]
> Hi @ItzCrazyKns
> 
> what was the solution? Would be nice to have a quick solution in the github issue to help people out that have the same problem.
> 
> Thanks a lot and have a nice day!

He didn't configured the config.toml file, so Docker thought it has a folder and linked it at as a volume. When FileSystem API is trying to execute read on it, it fails since its not a file but a folder. So configured the config.toml and delete the folder named config.toml

**Comment by Atomique** [comment]
Thanks a lot @ItzCrazyKns - You helped me to figure out that I had a small typo in my config path that I have overseen! 

First I had a wrong path in my config and it created a second config path. I "corrected" this and deleted the old and wrong path but did again a small typo in my path. A bit of a silly issue and definitely my fault. 

Thanks for helping me out with this, now I can try out perplexica
