### ISSUE TITLE
Missing line in backend.dockerfile

### ISSUE THREAD

**Issue by DuckY-Y** [ItzCrazyKns/Perplexica#390]
[1680](https://github.com/ItzCrazyKns/Perplexica/commit/1680a1786e7e81122c36743d580a4caafe19612e) as of writing this.

I cloned the git for an update, building went good. deploying went wrong.
There is a missing `COPY config.toml /home/perplexica/` line in backend.dockerfile.
resulting in the following errors:
```
perplexica-backend  | yarn run v1.22.22
perplexica-backend  | $ npm run db:push && node dist/app.js
perplexica-backend  |
perplexica-backend  | > perplexica-backend@1.9.0-rc3 db:push
perplexica-backend  | > drizzle-kit push sqlite
perplexica-backend  |
perplexica-backend  | drizzle-kit: v0.22.7
perplexica-backend  | drizzle-orm: v0.31.2
perplexica-backend  |
perplexica-backend  | No config path provided, using default path
perplexica-backend  | Reading config file '/home/perplexica/drizzle.config.ts'
perplexica-backend  | [⣷] Pulling schema from database...
[✓] Pulling schema from database...
perplexica-backend  |
perplexica-backend  | [i] No changes detected
perplexica-backend  | node:fs:441
perplexica-backend  |     return binding.readFileUtf8(path, stringToFlags(options.flag));
perplexica-backend  |                    ^
perplexica-backend  |
perplexica-backend  | Error: ENOENT: no such file or directory, open '/home/perplexica/config.toml'
perplexica-backend  |     at Object.readFileSync (node:fs:441:20)
perplexica-backend  |     at loadConfig (/home/perplexica/dist/config.js:11:60)
perplexica-backend  |     at getPort (/home/perplexica/dist/config.js:12:23)
perplexica-backend  |     at Object.<anonymous> (/home/perplexica/dist/app.js:13:35)
perplexica-backend  |     at Module._compile (node:internal/modules/cjs/loader:1546:14)
perplexica-backend  |     at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
perplexica-backend  |     at Module.load (node:internal/modules/cjs/loader:1317:32)
perplexica-backend  |     at Module._load (node:internal/modules/cjs/loader:1127:12)
perplexica-backend  |     at TracingChannel.traceSync (node:diagnostics_channel:315:14)
perplexica-backend  |     at wrapModuleLoad (node:internal/modules/cjs/loader:217:24) {
perplexica-backend  |   errno: -2,
perplexica-backend  |   code: 'ENOENT',
perplexica-backend  |   syscall: 'open',
perplexica-backend  |   path: '/home/perplexica/config.toml'
perplexica-backend  | }
perplexica-backend  |
perplexica-backend  | Node.js v22.9.0
perplexica-backend  | error Command failed with exit code 1.
perplexica-backend  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Pretty self explanatory.

**Comment by ItzCrazyKns** [comment]
Update Perplexica to the latest commits, config.toml isn't being copied because there isn't a need for it. We while running images link it as a volume so it doesn't gets updated on new updates, while building images there exists no config.toml file.

**Comment by ItzCrazyKns** [comment]
> I'm getting the same error can you please tell me how you fixed it ?

Delete the folder named config.toml and rename sample.config.toml to config.toml and rerun `docker compose up -d`
