### ISSUE TITLE
Trying to build fails to find python , older version worked 

### ISSUE THREAD

**Issue by Robabrown** [ItzCrazyKns/Perplexica#413]
**Describe the bug**
image is not building and it's not finding python distro,
my ollama is on another server so according to the instructions I shouldn't use the provided image

**To Reproduce**
I've tried this on 2 systems using docker, the older version worked 
1. clone the repo
2. docker compose up -d --build
3. 

**Expected behavior**
docker image should build 
**Screenshots**
9.056 prebuild-install warn install No prebuilt binaries found (target=23.0.0 runtime=node arch=x64 libc= platform=linux)
9.056 gyp info it worked if it ends with ok
9.056 gyp info using node-gyp@10.2.0
9.056 gyp info using node@23.0.0 | linux | x64
9.056 gyp ERR! find Python
9.056 gyp ERR! find Python Python is not set from command line or npm configuration
9.056 gyp ERR! find Python Python is not set from environment variable PYTHON
9.056 gyp ERR! find Python checking if "python3" can be used
9.056 gyp ERR! find Python - executable path is ""
9.056 gyp ERR! find Python - "" could not be run
9.056 gyp ERR! find Python checking if "python" can be used
9.056 gyp ERR! find Python - executable path is ""
9.056 gyp ERR! find Python - "" could not be run
9.056 gyp ERR! find Python
9.056 gyp ERR! find Python **********************************************************
9.056 gyp ERR! find Python You need to install the latest version of Python.
9.056 gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
9.056 gyp ERR! find Python you can try one of the following options:
9.056 gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
9.056 gyp ERR! find Python (accepted by both node-gyp and npm)
9.056 gyp ERR! find Python - Set the environment variable PYTHON
9.056 gyp ERR! find Python - Set the npm configuration variable python:
9.056 gyp ERR! find Python npm config set python "/path/to/pythonexecutable"
9.056 gyp ERR! find Python For more information consult the documentation at:
9.056 gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
9.056 gyp ERR! find Python **********************************************************
9.056 gyp ERR! find Python
9.056 gyp ERR! configure error
9.056 gyp ERR! stack Error: Could not find any Python installation to use
9.056 gyp ERR! stack at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:306:11)
9.056 gyp ERR! stack at PythonFinder.findPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:164:17)
9.056 gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
9.056 gyp ERR! stack at async configure (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:27:18)
9.056 gyp ERR! stack at async run (/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:81:18)
9.056 gyp ERR! System Linux 5.15.0-124-generic
9.056 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
9.056 gyp ERR! cwd /home/perplexica/node_modules/better-sqlite3
9.056 gyp ERR! node -v v23.0.0
9.056 gyp ERR! node-gyp -v v10.2.0
9.056 gyp ERR! not ok
------
failed to solve: process "/bin/sh -c yarn install --frozen-lockfile" did not complete successfully: exit code: 1

**Additional context**

**Comment by ItzCrazyKns** [comment]
Can you share the contents of `backend.dockerfile`

**Comment by Robabrown** [comment]
thanks for the quick reply... I solved it by updating the backend.dockerfile to "FROM node:18-slim'

**Comment by ItzCrazyKns** [comment]
Glad to know it worked, what was the previous base image you we're using? I've recently updated it to `node:20-buster` which contains Python
