### ISSUE TITLE
Latest docker image broken (tag is 2024.10.29-b183e620d)

### ISSUE THREAD

**Issue by baskinsy** [ItzCrazyKns/Perplexica#439]
**Describe the bug**
Latest docker image with tag ```2024.10.29-b183e620d``` is broken. An "Internal server error" message is displayed.

**To Reproduce**

1. Pull the latest image with ```docker compose pull```
2. Stop older running instance with ```docker compose down```
3. Start the instance with ```docker compose up -d```

**Expected behavior**
Image should work as expected.

**Additional context**
Reverting to image with tag ```2024.10.29-e39289257``` solves the issue.

Logs with the broken image

```
searxng  | SearXNG version 2024.10.29+b183e620d
searxng  | Use existing /etc/searxng/uwsgi.ini
searxng  | Use existing /etc/searxng/settings.yml
searxng  | Listen on 0.0.0.0:8080
searxng  | [uWSGI] getting INI configuration from /etc/searxng/uwsgi.ini
searxng  | [uwsgi-static] added mapping for /static => /usr/local/searxng/searx/static
searxng  | *** Starting uWSGI 2.0.25.1 (64bit) on [Tue Oct 29 14:40:40 2024] ***
searxng  | compiled with version: 13.2.1 20240309 on 17 May 2024 06:11:37
searxng  | os: Linux-6.8.0-47-generic #47-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 21:40:26 UTC 2024
searxng  | nodename: 742312eb2ab2
searxng  | machine: x86_64
searxng  | clock source: unix
searxng  | pcre jit disabled
searxng  | detected number of CPU cores: 2
searxng  | current working directory: /usr/local/searxng
searxng  | detected binary path: /usr/sbin/uwsgi
searxng  | setgid() to 977
searxng  | setuid() to 977
searxng  | chdir() to /usr/local/searxng/searx/
searxng  | your memory page size is 4096 bytes
searxng  | detected max file descriptor number: 1048576
searxng  | building mime-types dictionary from file /etc/mime.types...1390 entry found
searxng  | lock engine: pthread robust mutexes
searxng  | thunder lock: disabled (you can enable it with --thunder-lock)
searxng  | uwsgi socket 0 bound to TCP address 0.0.0.0:8080 fd 3
searxng  | Python version: 3.12.7 (main, Oct  7 2024, 11:30:19) [GCC 13.2.1 20240309]
searxng  | Python main interpreter initialized at 0x7c69acda6950
searxng  | python threads support enabled
searxng  | your server socket listen backlog is limited to 100 connections
searxng  | your mercy for graceful operations on workers is 60 seconds
searxng  | mapped 362016 bytes (353 KB) for 8 cores
searxng  | *** Operational MODE: preforking+threaded ***
searxng  | added /usr/local/searxng/ to pythonpath.
searxng  | spawned uWSGI master process (pid: 8)
searxng  | spawned uWSGI worker 1 (pid: 11, cores: 4)
searxng  | spawned uWSGI worker 2 (pid: 12, cores: 4)
searxng  | spawned 4 offload threads for uWSGI worker 1
searxng  | spawned 4 offload threads for uWSGI worker 2
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/local/searxng/searx/webapp.py", line 1355, in <module>
searxng  |     favicons.init()
searxng  |   File "/usr/local/searxng/searx/favicons/__init__.py", line 34, in init
searxng  |     cfg = config.FaviconConfig.from_toml_file(cfg_file, use_cache=True)
searxng  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/local/searxng/searx/favicons/config.py", line 49, in from_toml_file
searxng  |     cfg = msgspec.toml.decode(data, type=_FaviconConfig)
searxng  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/msgspec/toml.py", line 183, in decode
searxng  |     return _convert(
searxng  |            ^^^^^^^^^
searxng  | msgspec.ValidationError: Expected `Path`, got `str` - at `$.favicons.cache.db_url`
searxng  | unable to load app 0 (mountpoint='') (callable not found or import error)
searxng  | *** no app loaded. going in full dynamic mode ***
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/local/searxng/searx/webapp.py", line 1355, in <module>
searxng  |     favicons.init()
searxng  |   File "/usr/local/searxng/searx/favicons/__init__.py", line 34, in init
searxng  |     cfg = config.FaviconConfig.from_toml_file(cfg_file, use_cache=True)
searxng  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/local/searxng/searx/favicons/config.py", line 49, in from_toml_file
searxng  |     cfg = msgspec.toml.decode(data, type=_FaviconConfig)
searxng  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/msgspec/toml.py", line 183, in decode
searxng  |     return _convert(
searxng  |            ^^^^^^^^^
searxng  | msgspec.ValidationError: Expected `Path`, got `str` - at `$.favicons.cache.db_url`
searxng  | unable to load app 0 (mountpoint='') (callable not found or import error)
searxng  | *** no app loaded. going in full dynamic mode ***
searxng  | 2024-10-29 14:40:44,604 ERROR:searx.engines.soundcloud: Fail to initialize
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/lib/python3.12/site-packages/anyio/streams/tls.py", line 140, in _call_sslobject_method
searxng  |     result = func(*args)
searxng  |              ^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/ssl.py", line 858, in read
searxng  |     v = self._sslobj.read(len)
searxng  |         ^^^^^^^^^^^^^^^^^^^^^^
searxng  | ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2570)
searxng  | 
searxng  | During handling of the above exception, another exception occurred:
searxng  | 
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/lib/python3.12/site-packages/anyio/_core/_tasks.py", line 115, in fail_after
searxng  |     yield cancel_scope
searxng  |   File "/usr/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 34, in read
searxng  |     return await self._stream.receive(max_bytes=max_bytes)
searxng  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/anyio/streams/tls.py", line 204, in receive
searxng  |     data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
searxng  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/anyio/streams/tls.py", line 147, in _call_sslobject_method
searxng  |     data = await self.transport_stream.receive()
searxng  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 1227, in receive
searxng  |     await self._protocol.read_event.wait()
searxng  |   File "/usr/lib/python3.12/asyncio/locks.py", line 212, in wait
searxng  |     await fut
searxng  | asyncio.exceptions.CancelledError: Cancelled by cancel scope 7c69a7dce810
searxng  | 
searxng  | During handling of the above exception, another exception occurred:
searxng  | 
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/lib/python3.12/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
searxng  |     yield
searxng  |   File "/usr/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 32, in read
searxng  |     with anyio.fail_after(timeout):
searxng  |          ^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
searxng  |     self.gen.throw(value)
searxng  |   File "/usr/lib/python3.12/site-packages/anyio/_core/_tasks.py", line 118, in fail_after
searxng  |     raise TimeoutError
searxng  | TimeoutError
searxng  | 
searxng  | The above exception was the direct cause of the following exception:
searxng  | 
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/lib/python3.12/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
searxng  |     yield
searxng  |   File "/usr/lib/python3.12/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
searxng  |     resp = await self._pool.handle_async_request(req)
searxng  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 262, in handle_async_request
searxng  |     raise exc
searxng  |   File "/usr/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 245, in handle_async_request
searxng  |     response = await connection.handle_async_request(request)
searxng  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/httpcore/_async/connection.py", line 96, in handle_async_request
searxng  |     return await self._connection.handle_async_request(request)
searxng  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/httpcore/_async/http2.py", line 185, in handle_async_request
searxng  |     raise exc
searxng  |   File "/usr/lib/python3.12/site-packages/httpcore/_async/http2.py", line 148, in handle_async_request
searxng  |     status, headers = await self._receive_response(
searxng  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/httpcore/_async/http2.py", line 292, in _receive_response
searxng  |     event = await self._receive_stream_event(request, stream_id)
searxng  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/httpcore/_async/http2.py", line 333, in _receive_stream_event
searxng  |     await self._receive_events(request, stream_id)
searxng  |   File "/usr/lib/python3.12/site-packages/httpcore/_async/http2.py", line 361, in _receive_events
searxng  |     events = await self._read_incoming_data(request)
searxng  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/httpcore/_async/http2.py", line 452, in _read_incoming_data
searxng  |     raise exc
searxng  |   File "/usr/lib/python3.12/site-packages/httpcore/_async/http2.py", line 438, in _read_incoming_data
searxng  |     data = await self._network_stream.read(self.READ_NUM_BYTES, timeout)
searxng  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 31, in read
searxng  |     with map_exceptions(exc_map):
searxng  |          ^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
searxng  |     self.gen.throw(value)
searxng  |   File "/usr/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
searxng  |     raise to_exc(exc) from exc
searxng  | httpcore.ReadTimeout
searxng  | 
searxng  | The above exception was the direct cause of the following exception:
searxng  | 
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/local/searxng/searx/search/processors/abstract.py", line 73, in initialize
searxng  |     self.engine.init(get_engine_from_settings(self.engine_name))
searxng  |   File "/usr/local/searxng/searx/engines/soundcloud.py", line 69, in init
searxng  |     guest_client_id = get_client_id()
searxng  |                       ^^^^^^^^^^^^^^^
searxng  |   File "/usr/local/searxng/searx/engines/soundcloud.py", line 45, in get_client_id
searxng  |     resp = http_get("https://soundcloud.com")
searxng  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/local/searxng/searx/network/__init__.py", line 164, in get
searxng  |     return request('get', url, **kwargs)
searxng  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/local/searxng/searx/network/__init__.py", line 95, in request
searxng  |     return future.result(timeout)
searxng  |            ^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/concurrent/futures/_base.py", line 456, in result
searxng  |     return self.__get_result()
searxng  |            ^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
searxng  |     raise self._exception
searxng  |   File "/usr/local/searxng/searx/network/network.py", line 289, in request
searxng  |     return await self.call_client(False, method, url, **kwargs)
searxng  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/local/searxng/searx/network/network.py", line 285, in call_client
searxng  |     raise e
searxng  |   File "/usr/local/searxng/searx/network/network.py", line 270, in call_client
searxng  |     response = await client.request(method, url, **kwargs)
searxng  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/httpx/_client.py", line 1530, in request
searxng  |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
searxng  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/httpx/_client.py", line 1617, in send
searxng  |     response = await self._send_handling_auth(
searxng  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
searxng  |     response = await self._send_handling_redirects(
searxng  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
searxng  |     response = await self._send_single_request(request)
searxng  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/httpx/_client.py", line 1719, in _send_single_request
searxng  |     response = await transport.handle_async_request(request)
searxng  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
searxng  |     with map_httpcore_exceptions():
searxng  |          ^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
searxng  |     self.gen.throw(value)
searxng  |   File "/usr/lib/python3.12/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
searxng  |     raise mapped_exc(message) from exc
searxng  | httpx.ReadTimeout
searxng  | 2024-10-29 14:40:44,617 ERROR:searx.engines.soundcloud: Fail to initialize
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/lib/python3.12/site-packages/anyio/streams/tls.py", line 140, in _call_sslobject_method
searxng  |     result = func(*args)
searxng  |              ^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/ssl.py", line 858, in read
searxng  |     v = self._sslobj.read(len)
searxng  |         ^^^^^^^^^^^^^^^^^^^^^^
searxng  | ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2570)
searxng  | 
searxng  | During handling of the above exception, another exception occurred:
searxng  | 
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/lib/python3.12/site-packages/anyio/_core/_tasks.py", line 115, in fail_after
searxng  |     yield cancel_scope
searxng  |   File "/usr/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 34, in read
searxng  |     return await self._stream.receive(max_bytes=max_bytes)
searxng  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/anyio/streams/tls.py", line 204, in receive
searxng  |     data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
searxng  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/anyio/streams/tls.py", line 147, in _call_sslobject_method
searxng  |     data = await self.transport_stream.receive()
searxng  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 1227, in receive
searxng  |     await self._protocol.read_event.wait()
searxng  |   File "/usr/lib/python3.12/asyncio/locks.py", line 212, in wait
searxng  |     await fut
searxng  | asyncio.exceptions.CancelledError: Cancelled by cancel scope 7c69a81d7200
searxng  | 
searxng  | During handling of the above exception, another exception occurred:
searxng  | 
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/lib/python3.12/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
searxng  |     yield
searxng  |   File "/usr/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 32, in read
searxng  |     with anyio.fail_after(timeout):
searxng  |          ^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
searxng  |     self.gen.throw(value)
searxng  |   File "/usr/lib/python3.12/site-packages/anyio/_core/_tasks.py", line 118, in fail_after
searxng  |     raise TimeoutError
searxng  | TimeoutError
searxng  | 
searxng  | The above exception was the direct cause of the following exception:
searxng  | 
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/lib/python3.12/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
searxng  |     yield
searxng  |   File "/usr/lib/python3.12/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
searxng  |     resp = await self._pool.handle_async_request(req)
searxng  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 262, in handle_async_request
searxng  |     raise exc
searxng  |   File "/usr/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 245, in handle_async_request
searxng  |     response = await connection.handle_async_request(request)
searxng  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/httpcore/_async/connection.py", line 96, in handle_async_request
searxng  |     return await self._connection.handle_async_request(request)
searxng  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/httpcore/_async/http2.py", line 185, in handle_async_request
searxng  |     raise exc
searxng  |   File "/usr/lib/python3.12/site-packages/httpcore/_async/http2.py", line 148, in handle_async_request
searxng  |     status, headers = await self._receive_response(
searxng  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/httpcore/_async/http2.py", line 292, in _receive_response
searxng  |     event = await self._receive_stream_event(request, stream_id)
searxng  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/httpcore/_async/http2.py", line 333, in _receive_stream_event
searxng  |     await self._receive_events(request, stream_id)
searxng  |   File "/usr/lib/python3.12/site-packages/httpcore/_async/http2.py", line 361, in _receive_events
searxng  |     events = await self._read_incoming_data(request)
searxng  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/httpcore/_async/http2.py", line 452, in _read_incoming_data
searxng  |     raise exc
searxng  |   File "/usr/lib/python3.12/site-packages/httpcore/_async/http2.py", line 438, in _read_incoming_data
searxng  |     data = await self._network_stream.read(self.READ_NUM_BYTES, timeout)
searxng  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 31, in read
searxng  |     with map_exceptions(exc_map):
searxng  |          ^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
searxng  |     self.gen.throw(value)
searxng  |   File "/usr/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
searxng  |     raise to_exc(exc) from exc
searxng  | httpcore.ReadTimeout
searxng  | 
searxng  | The above exception was the direct cause of the following exception:
searxng  | 
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/local/searxng/searx/search/processors/abstract.py", line 73, in initialize
searxng  |     self.engine.init(get_engine_from_settings(self.engine_name))
searxng  |   File "/usr/local/searxng/searx/engines/soundcloud.py", line 69, in init
searxng  |     guest_client_id = get_client_id()
searxng  |                       ^^^^^^^^^^^^^^^
searxng  |   File "/usr/local/searxng/searx/engines/soundcloud.py", line 45, in get_client_id
searxng  |     resp = http_get("https://soundcloud.com")
searxng  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/local/searxng/searx/network/__init__.py", line 164, in get
searxng  |     return request('get', url, **kwargs)
searxng  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/local/searxng/searx/network/__init__.py", line 95, in request
searxng  |     return future.result(timeout)
searxng  |            ^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/concurrent/futures/_base.py", line 456, in result
searxng  |     return self.__get_result()
searxng  |            ^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
searxng  |     raise self._exception
searxng  |   File "/usr/local/searxng/searx/network/network.py", line 289, in request
searxng  |     return await self.call_client(False, method, url, **kwargs)
searxng  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/local/searxng/searx/network/network.py", line 285, in call_client
searxng  |     raise e
searxng  |   File "/usr/local/searxng/searx/network/network.py", line 270, in call_client
searxng  |     response = await client.request(method, url, **kwargs)
searxng  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/httpx/_client.py", line 1530, in request
searxng  |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
searxng  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/httpx/_client.py", line 1617, in send
searxng  |     response = await self._send_handling_auth(
searxng  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
searxng  |     response = await self._send_handling_redirects(
searxng  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
searxng  |     response = await self._send_single_request(request)
searxng  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/httpx/_client.py", line 1719, in _send_single_request
searxng  |     response = await transport.handle_async_request(request)
searxng  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
searxng  |     with map_httpcore_exceptions():
searxng  |          ^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
searxng  |     self.gen.throw(value)
searxng  |   File "/usr/lib/python3.12/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
searxng  |     raise mapped_exc(message) from exc
searxng  | httpx.ReadTimeout
searxng  | --- no python application found, check your startup logs for errors ---
searxng  | [pid: 11|app: -1|req: -1/1] 10.10.10.106 () {56 vars in 1780 bytes} [Tue Oct 29 14:40:50 2024] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 3 headers in 102 bytes (0 switches on core 0)
searxng  | --- no python application found, check your startup logs for errors ---
searxng  | [pid: 12|app: -1|req: -1/2] 10.10.10.106 () {56 vars in 1780 bytes} [Tue Oct 29 14:40:51 2024] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 3 headers in 102 bytes (0 switches on core 0)
```

**Comment by ItzCrazyKns** [comment]
Seems like some issue with SearXNG, I tried pulling the latest images and am not able to replicate the issue. Please use the following commands:

1. `docker compose pull`
2. `docker compose up -d`

This should fix your issue, if not please contact SearXNG support. Or feel free to reopen this isse.

**Comment by baskinsy** [comment]
What is the latest tag? I can see it is the ```[2024.10.29-b183e620d](https://hub.docker.com/layers/searxng/searxng/2024.10.29-b183e620d/images/sha256-64bd5555875ff4aa543a42cfb74bc1540477714c151e06b32e6db5494035ae5c?context=explore)".

When I pull it it trows the error, reverting to the previous one works. Maybe has to do with the favicons settings?

**Comment by baskinsy** [comment]
I am reopening the issue because the latest image still is broken for me at least.  I cleaned all images pull again and the same issue persists. Image with tag ```2024.10.29-e39289257``` works as expected.

**Comment by baskinsy** [comment]
This seems to mean something.

```
searxng  | msgspec.ValidationError: Expected `Path`, got `str` - at `$.favicons.cache.db_url`
searxng  | unable to load app 0 (mountpoint='') (callable not found or import error)
```

**Comment by baskinsy** [comment]
My bad, I opened the issue in the wrong project by mistake, sorry for the noise.
