### ISSUE TITLE
v1.1.0  error: Error loading Ollama models: SyntaxError: Unexpected token p in JSON at position 4

### ISSUE THREAD

**Issue by futurewin** [ItzCrazyKns/Perplexica#52]
**Describe the bug**
use docker ollama  ( browser can visit http://127.0.0.1:11434/api/tags  ,there is a llama3 modal in it)
use Non-Docker Perplexica 1.1.0

in settings fill with "http://127.0.0.1:11434" in Ollama API URL ,then fetch ,error msg "error: Error loading Ollama models: SyntaxError: Unexpected token p in JSON at position 4"

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by edisonzf2020** [comment]
+1

**Comment by ItzCrazyKns** [comment]
Seems like Perplexica's backend is getting malformed JSON response from Ollama. Can you provide a screenshot of what the API endpoint for tags is returning?

**Comment by futurewin** [comment]
> Seems like Perplexica's backend is getting malformed JSON response from Ollama. Can you provide a screenshot of what the API endpoint for tags is returning?


this i press the cloud button return

![Uploading Screenshot from 2024-05-03 18-12-10.png…]()

**Comment by futurewin** [comment]
> Seems like Perplexica's backend is getting malformed JSON response from Ollama. Can you provide a screenshot of what the API endpoint for tags is returning?


There is no this bug in v1.0.0 .

I press the cloud button return this in v 1.1.0

![Screenshot from 2024-05-03 18-12-10](https://github.com/ItzCrazyKns/Perplexica/assets/47633902/0cbe3507-d44e-4087-8346-47d6c78c8cab)

**Comment by futurewin** [comment]
I just test  v1.2.1 ,still have this bug ,can't see modals.

system: ubuntu24.04
ollama: non docker install , can see api in http://127.0.0.1:11434/api/tags
Perplexica: non docker install 

after open the setting, only see Ollama title ,but can't see modals
![Screenshot from 2024-05-03 18-56-45](https://github.com/ItzCrazyKns/Perplexica/assets/47633902/20ec9857-65ca-49e2-a745-70977327f4ab)


after press the cloud button ,no error msg show in the terminator
![Screenshot from 2024-05-03 18-57-12](https://github.com/ItzCrazyKns/Perplexica/assets/47633902/3b00fdec-9690-4884-8bb6-527c207b0ca1)

**Comment by ItzCrazyKns** [comment]
Can you show the logs from the backend container, I think the Ollama API URL is invalid

**Comment by futurewin** [comment]
I just test v1.3.1 ,can select models, but after pressing the cloud button ,a error message show in the browser "Invalid LLM or embedding model select" . no error message in backend terminator

system: ubuntu24.04
ollama: non docker install , can see api in http://127.0.0.1:11434/api/tags or http://localhost:11434/api/tags
Perplexica: non docker install

after open the setting, can see Ollama title ,can select llms , but after pressing the cloud button , error happen ,can't chat with llm

![Screenshot from 2024-05-04 19-52-55](https://github.com/ItzCrazyKns/Perplexica/assets/47633902/732f41ad-44e5-4f51-b427-c5f6410d461c)

**Comment by ItzCrazyKns** [comment]
Can you show the logs from the backend container

**Comment by ItzCrazyKns** [comment]
> I just test v1.3.1 ,can select models, but after pressing the cloud button ,a error message show in the browser "Invalid LLM or embedding model select" . no error message in backend terminator
> 
> system: ubuntu24.04 ollama: non docker install , can see api in http://127.0.0.1:11434/api/tags or http://localhost:11434/api/tags Perplexica: non docker install
> 
> after open the setting, can see Ollama title ,can select llms , but after pressing the cloud button , error happen ,can't chat with llm
> 
> ![Screenshot from 2024-05-04 19-52-55](https://private-user-images.githubusercontent.com/47633902/327980763-732f41ad-44e5-4f51-b427-c5f6410d461c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MTA5MTYsIm5iZiI6MTcxNDkxMDYxNiwicGF0aCI6Ii80NzYzMzkwMi8zMjc5ODA3NjMtNzMyZjQxYWQtNDRlNS00ZjUxLWI0MjctYzVmNjQxMGQ0NjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDEyMDMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyM2UyYzgxN2FmOWJhYjQwNzc0ZjdkNTAxNDUwYWE5YzZjMTgzZjk5YTU3YjIwYmIxYWI3OTBmNzk2OTdhZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JqzTx5AYjqjksaBjad3_ZClenJ0Ttdtg2KDwgny0SgU)
> 
> ![Screenshot from 2024-05-04 20-07-35](https://private-user-images.githubusercontent.com/47633902/327981034-b155f33e-dd05-4a50-a9c5-7fe1b188313c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MTA5MTYsIm5iZiI6MTcxNDkxMDYxNiwicGF0aCI6Ii80NzYzMzkwMi8zMjc5ODEwMzQtYjE1NWYzM2UtZGQwNS00YTUwLWE5YzUtN2ZlMWIxODgzMTNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDEyMDMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4YWY3ZTYwMTU5YTAyMTZiMDY4YzUxMTdhMzY1NGY5NWU4NzA0Y2MxNmU1OGVkZDA0MTA4YTcwNDUzNGU2NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2tjP4FBHtf8zKAE0NO7rr2XykH3fhC_OIGinbl9c7d0) ![Screenshot from 2024-05-04 20-06-34](https://private-user-images.githubusercontent.com/47633902/327981041-3368042d-0a7f-4f1a-b94a-20daa8ce9ed3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MTA5MTYsIm5iZiI6MTcxNDkxMDYxNiwicGF0aCI6Ii80NzYzMzkwMi8zMjc5ODEwNDEtMzM2ODA0MmQtMGE3Zi00ZjFhLWI5NGEtMjBkYWE4Y2U5ZWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDEyMDMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjNDlmNzQxNDlhZGE3YWE1YzhmNDA3MjFkM2VhNzkzNzM1MzU3NjFmMzU5MTljZGQ2NmQwNGFlMzY1ZGRhYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8o0ujo_n1vuobGdR2y4RZp6JLyJreizgZI0pqGag3xo) ![Screenshot from 2024-05-04 20-05-37](https://private-user-images.githubusercontent.com/47633902/327981042-c85d216e-5464-44d0-bd74-4431c907f8b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MTA5MTYsIm5iZiI6MTcxNDkxMDYxNiwicGF0aCI6Ii80NzYzMzkwMi8zMjc5ODEwNDItYzg1ZDIxNmUtNTQ2NC00NGQwLWJkNzQtNDQzMWM5MDdmOGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDEyMDMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmODYxMWRlMjJiNzZhYjkyZjAxZmYxYTkxOWM3YmU3MmJiZmNkNGNlZjc1NDViMzU4YmI0NDEwOGMwYWE1MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AmC6y8Gy_r9hWOlEmhHyovWJSa-CLJ_fPrD7F2lml-s)

Hi, update to 1.3.2. It should fix the issues.

**Comment by futurewin** [comment]
well done,in v1.3.2. you have fixed the bug that cant select models. 
Then  i  found  another 2 questions in v1.3.2:

Q1:  in settings  i  can select models in chat model and embedding model , but only chat model can activate. how to use embedding model?

![Screenshot from 2024-05-05 18-36-54](https://github.com/ItzCrazyKns/Perplexica/assets/47633902/026c1e1a-d62f-4259-a6ac-4038cce50448)

Q2: when I use All mode to chat  , then v1.3.2 backend crashed, can you fix it ? the backend  error msg is:
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^
AxiosError: connect ECONNREFUSED 127.0.0.1:32768
    at AxiosError.from (/home/Perplexica/node_modules/axios/dist/node/axios.cjs:836:14)
    at RedirectableRequest.handleRequestError (/home/Perplexica/node_modules/axios/dist/node/axios.cjs:3086:25)
    at RedirectableRequest.emit (node:events:517:28)
    at eventHandlers.<computed> (/home/Perplexica/node_modules/follow-redirects/index.js:38:24)
    at ClientRequest.emit (node:events:517:28)
    at Socket.socketErrorListener (node:_http_client:501:9)
    at Socket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (/home/Perplexica/node_modules/axios/dist/node/axios.cjs:3876:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async searchSearxng (/home/Perplexica/dist/lib/searxng.js:22:17)
    at async RunnableLambda.func (/home/Perplexica/dist/agents/webSearchAgent.js:82:25)
    at async /home/Perplexica/node_modules/@langchain/core/dist/runnables/base.cjs:1385:33 {
  port: 32768,
  address: '127.0.0.1',
  syscall: 'connect',
  code: 'ECONNREFUSED',
  errno: -111,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: {
      FormData: [Function: FormData] {
        LINE_BREAK: '\r\n',
        DEFAULT_CONTENT_TYPE: 'application/octet-stream'
      },
      Blob: [class Blob]
    },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': undefined,
      'User-Agent': 'axios/1.6.8',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'get',
    url: 'http://localhost:32768/search?format=json&q=Not+needed&language=en',
    data: undefined
  },
  request: <ref *2> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'http:',
      path: '/search?format=json&q=Not+needed&language=en',
      method: 'GET',
      headers: [Object: null prototype] {
        Accept: 'application/json, text/plain, */*',
        'User-Agent': 'axios/1.6.8',
        'Accept-Encoding': 'gzip, compress, deflate, br'
      },
      agents: { http: undefined, https: undefined },
      auth: undefined,
      family: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: { proxy: [Function: beforeRedirect] },
      hostname: 'localhost',
      port: '32768',
      agent: undefined,
      nativeProtocols: {
        'http:': {
          _connectionListener: [Function: connectionListener],
          METHODS: [
            'ACL',         'BIND',       'CHECKOUT',
            'CONNECT',     'COPY',       'DELETE',
            'GET',         'HEAD',       'LINK',
            'LOCK',        'M-SEARCH',   'MERGE',
            'MKACTIVITY',  'MKCALENDAR', 'MKCOL',
            'MOVE',        'NOTIFY',     'OPTIONS',
            'PATCH',       'POST',       'PROPFIND',
            'PROPPATCH',   'PURGE',      'PUT',
            'REBIND',      'REPORT',     'SEARCH',
            'SOURCE',      'SUBSCRIBE',  'TRACE',
            'UNBIND',      'UNLINK',     'UNLOCK',
            'UNSUBSCRIBE'
          ],
          STATUS_CODES: {
            '100': 'Continue',
            '101': 'Switching Protocols',
            '102': 'Processing',
            '103': 'Early Hints',
            '200': 'OK',
            '201': 'Created',
            '202': 'Accepted',
            '203': 'Non-Authoritative Information',
            '204': 'No Content',
            '205': 'Reset Content',
            '206': 'Partial Content',
            '207': 'Multi-Status',
            '208': 'Already Reported',
            '226': 'IM Used',
            '300': 'Multiple Choices',
            '301': 'Moved Permanently',
            '302': 'Found',
            '303': 'See Other',
            '304': 'Not Modified',
            '305': 'Use Proxy',
            '307': 'Temporary Redirect',
            '308': 'Permanent Redirect',
            '400': 'Bad Request',
            '401': 'Unauthorized',
            '402': 'Payment Required',
            '403': 'Forbidden',
            '404': 'Not Found',
            '405': 'Method Not Allowed',
            '406': 'Not Acceptable',
            '407': 'Proxy Authentication Required',
            '408': 'Request Timeout',
            '409': 'Conflict',
            '410': 'Gone',
            '411': 'Length Required',
            '412': 'Precondition Failed',
            '413': 'Payload Too Large',
            '414': 'URI Too Long',
            '415': 'Unsupported Media Type',
            '416': 'Range Not Satisfiable',
            '417': 'Expectation Failed',
            '418': "I'm a Teapot",
            '421': 'Misdirected Request',
            '422': 'Unprocessable Entity',
            '423': 'Locked',
            '424': 'Failed Dependency',
            '425': 'Too Early',
            '426': 'Upgrade Required',
            '428': 'Precondition Required',
            '429': 'Too Many Requests',
            '431': 'Request Header Fields Too Large',
            '451': 'Unavailable For Legal Reasons',
            '500': 'Internal Server Error',
            '501': 'Not Implemented',
            '502': 'Bad Gateway',
            '503': 'Service Unavailable',
            '504': 'Gateway Timeout',
            '505': 'HTTP Version Not Supported',
            '506': 'Variant Also Negotiates',
            '507': 'Insufficient Storage',
            '508': 'Loop Detected',
            '509': 'Bandwidth Limit Exceeded',
            '510': 'Not Extended',
            '511': 'Network Authentication Required'
          },
          Agent: [Function: Agent] { defaultMaxSockets: Infinity },
          ClientRequest: [Function: ClientRequest],
          IncomingMessage: [Function: IncomingMessage],
          OutgoingMessage: [Function: OutgoingMessage],
          Server: [Function: Server],
          ServerResponse: [Function: ServerResponse],
          createServer: [Function: createServer],
          validateHeaderName: [Function: __node_internal_],
          validateHeaderValue: [Function: __node_internal_],
          get: [Function: get],
          request: [Function: request],
          setMaxIdleHTTPParsers: [Function: setMaxIdleHTTPParsers],
          maxHeaderSize: [Getter],
          globalAgent: [Getter/Setter]
        },
        'https:': {
          Agent: [Function: Agent],
          globalAgent: Agent {
            _events: [Object: null prototype],
            _eventsCount: 2,
            _maxListeners: undefined,
            defaultPort: 443,
            protocol: 'https:',
            options: [Object: null prototype],
            requests: [Object: null prototype] {},
            sockets: [Object: null prototype] {},
            freeSockets: [Object: null prototype] {},
            keepAliveMsecs: 1000,
            keepAlive: false,
            maxSockets: Infinity,
            maxFreeSockets: 256,
            scheduling: 'lifo',
            maxTotalSockets: Infinity,
            totalSocketCount: 0,
            maxCachedSessions: 100,
            _sessionCache: [Object],
            [Symbol(kCapture)]: false
          },
          Server: [Function: Server],
          createServer: [Function: createServer],
          get: [Function: get],
          request: [Function: request]
        }
      },
      pathname: '/search',
      search: '?format=json&q=Not+needed&language=en'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: <ref *1> ClientRequest {
      _events: [Object: null prototype] {
        response: [Function: bound onceWrapper] {
          listener: [Function (anonymous)]
        },
        abort: [Function (anonymous)],
        aborted: [Function (anonymous)],
        connect: [Function (anonymous)],
        error: [Function (anonymous)],
        socket: [Function (anonymous)],
        timeout: [Function (anonymous)]
      },
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: Socket {
        connecting: false,
        _hadError: true,
        _parent: null,
        _host: 'localhost',
        _closeAfterHandlingError: false,
        _readableState: ReadableState {
          state: 62552,
          highWaterMark: 16384,
          buffer: BufferList { head: null, tail: null, length: 0 },
          length: 0,
          pipes: [],
          flowing: true,
          errored: Error: connect ECONNREFUSED 127.0.0.1:32768
              at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1549:16) {
            errno: -111,
            code: 'ECONNREFUSED',
            syscall: 'connect',
            address: '127.0.0.1',
            port: 32768
          },
          defaultEncoding: 'utf8',
          awaitDrainWriters: null,
          decoder: null,
          encoding: null,
          [Symbol(kPaused)]: false
        },
        _events: [Object: null prototype] {
          end: [Function: onReadableStreamEnd],
          connect: [ [Function], [Function], [Function] ],
          free: [Function: onFree],
          close: [
            [Function: onClose],
            [Function: socketCloseListener],
            [Function]
          ],
          timeout: [Function: onTimeout],
          agentRemove: [Function: onRemove],
          error: [Function: socketErrorListener],
          drain: [Function: ondrain]
        },
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: WritableState {
          objectMode: false,
          highWaterMark: 16384,
          finalCalled: false,
          needDrain: false,
          ending: false,
          ended: false,
          finished: false,
          destroyed: true,
          decodeStrings: false,
          defaultEncoding: 'utf8',
          length: 217,
          writing: true,
          corked: 0,
          sync: false,
          bufferProcessing: false,
          onwrite: [Function: bound onwrite],
          writecb: [Function: bound onFinish],
          writelen: 217,
          afterWriteTickInfo: null,
          buffered: [],
          bufferedIndex: 0,
          allBuffers: true,
          allNoop: true,
          pendingcb: 1,
          constructed: true,
          prefinished: false,
          errorEmitted: true,
          emitClose: false,
          autoDestroy: true,
          errored: Error: connect ECONNREFUSED 127.0.0.1:32768
              at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1549:16) {
            errno: -111,
            code: 'ECONNREFUSED',
            syscall: 'connect',
            address: '127.0.0.1',
            port: 32768
          },
          closed: true,
          closeEmitted: true,
          [Symbol(kOnFinished)]: []
        },
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: 'GET /search?format=json&q=Not+needed&language=en HTTP/1.1\r\n' +
          'Accept: application/json, text/plain, */*\r\n' +
          'User-Agent: axios/1.6.8\r\n' +
          'Accept-Encoding: gzip, compress, deflate, br\r\n' +
          'Host: localhost:32768\r\n' +
          'Connection: close\r\n' +
          '\r\n',
        _pendingEncoding: 'latin1',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular *1],
        [Symbol(async_id_symbol)]: 890,
        [Symbol(kHandle)]: null,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBuffer)]: null,
        [Symbol(kBufferCb)]: null,
        [Symbol(kBufferGen)]: null,
        [Symbol(kCapture)]: false,
        [Symbol(kSetNoDelay)]: true,
        [Symbol(kSetKeepAlive)]: true,
        [Symbol(kSetKeepAliveInitialDelay)]: 60,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0
      },
      _header: 'GET /search?format=json&q=Not+needed&language=en HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/1.6.8\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: localhost:32768\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: Agent {
        _events: [Object: null prototype] {
          free: [Function (anonymous)],
          newListener: [Function: maybeEnableKeylog]
        },
        _eventsCount: 2,
        _maxListeners: undefined,
        defaultPort: 80,
        protocol: 'http:',
        options: [Object: null prototype] { noDelay: true, path: null },
        requests: [Object: null prototype] {},
        sockets: [Object: null prototype] { 'localhost:32768:': [ [Socket] ] },
        freeSockets: [Object: null prototype] {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: Infinity,
        totalSocketCount: 1,
        [Symbol(kCapture)]: false
      },
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/search?format=json&q=Not+needed&language=en',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',
      _redirectable: [Circular *2],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype] {
        accept: [ 'Accept', 'application/json, text/plain, */*' ],
        'user-agent': [ 'User-Agent', 'axios/1.6.8' ],
        'accept-encoding': [ 'Accept-Encoding', 'gzip, compress, deflate, br' ],
        host: [ 'Host', 'localhost:32768' ]
      },
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'http://localhost:32768/search?format=json&q=Not+needed&language=en',
    [Symbol(kCapture)]: false
  },
  cause: Error: connect ECONNREFUSED 127.0.0.1:32768
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1549:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 32768
  }
}

Node.js v18.19.1

**Comment by futurewin** [comment]
and i suggest can add a "stop" button that can stop the model chats in loops..

![Screenshot from 2024-05-05 19-10-03](https://github.com/ItzCrazyKns/Perplexica/assets/47633902/fb29d9d2-eec4-43a0-b389-481733d57e4f)

**Comment by ItzCrazyKns** [comment]
1. The embedding model is used by the chain to perform similarity search, it is like a latent model in this cause so you won't see it in action but it is getting used.
2. You need to setup SearXNG in order to search the web, I think you are using non-Docker installation, SearXNG is pre-installed for the Docker installation method.
