### ISSUE TITLE
[BUG] TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by wwjCMP** [ItzCrazyKns/Perplexica#73]
**Describe the bug**

2024-05-06 12:41:18 yarn run v1.22.19
2024-05-06 12:41:18 $ node dist/app.js
2024-05-06 12:41:19 info: WebSocket server started on port 3011
2024-05-06 12:41:19 info: Server is running on port 3011
2024-05-06 15:11:41 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2024-05-06 12:41:19 (node:28) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
2024-05-06 12:41:19 (Use `node --trace-deprecation ...` to show where the warning was created)
2024-05-06 15:11:41 /home/perplexica/dist/agents/webSearchAgent.js:85
2024-05-06 15:11:41             const documents = res.results.map((result) => new documents_1.Document({
2024-05-06 15:11:41                                           ^
2024-05-06 15:11:41 
2024-05-06 15:11:41 TypeError: Cannot read properties of undefined (reading 'map')
2024-05-06 15:11:41     at RunnableLambda.func (/home/perplexica/dist/agents/webSearchAgent.js:85:43)
2024-05-06 15:11:41     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-05-06 15:11:41     at async /home/perplexica/node_modules/@langchain/core/dist/runnables/base.cjs:1385:33
2024-05-06 15:11:41 
2024-05-06 15:11:41 Node.js v22.1.0
2024-05-06 15:11:41 error Command failed with exit code 1.

**To Reproduce**

I first used Normal Mode, and then I used Copilot Mode.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ItzCrazyKns** [comment]
Co-pilot mode is under development and even if you use it, nothing would happen.

**Comment by datascience279** [comment]
@ItzCrazyKns when can we expect it?
